# -*- coding: utf-8 -*-
"""Aula1_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZtSfled783xolmj9ZnFqdqLUntbtQ6k

# Aula 01 - Exemplos

Versão simples
"""

# Aula 01 - Exemplos 01
nome = "João"       # variável do tipo str
idade = 25          # variável do tipo int
altura = 1.75       # variável do tipo float
estudante = True    # variável do tipo bool

print("Olá", nome)
print(f"Sua idade cadastrada é, {idade} anos.")
print(f"Foi informado que tem {altura} de altura e que é estudante.")

"""Versão com definição do tipo da variável"""

# Aula 01 - Exemplos 02
nome = input("Informe seu nome: ")       # variável do tipo str
idade = int(input("Informe sua idade: ")) # variável do tipo int
altura = float(input("Digite sua altura"))
estudante = bool(input("É estudante, digite True para sim")) # variável do tipo bool

print("Olá", nome)
print(f"Sua idade cadastrada é, {idade} anos.")
print(f"Foi informado que tem {altura} de altura e que é estudante.")

"""# Exercícios

Escreva um programa que leia o nome e a idade aluno. Peça três notas do aluno e exiba a média das notas
"""

# Aula 01 - Exercício 01
nome = input("Informe o nome do aluno: ")
nota1 = float(input("Informe a primeira nota --> "))
nota2 = float(input("Informe a segunda nota --> "))
nota3 = float(input("Informe a terceira nota --> "))

media = (nota1 + nota2 + nota3) / 3

print(f"A média do aluno {nome} é {media}")

"""Solicite um valor do usuário e mostre, como resultado, o dobro, o triplo e a raiz quadrada deste valor"""

# Aula 01 - Exercício 02
valor = float (input("Informe um valor númérico --> "))
dobro = valor *2
triplo = valor *3
raiz = valor **(1/2)
print(f"O valor informado foi {valor}")
print(f"O dobro do valor {valor} é {dobro}")
print(f"O triplo do valor {valor} é {triplo}")
print(f"A raiz quadrada do valor {valor} é {raiz}")

"""Receba dois valores numéricos e exiba a soma, diferença, produto e divisão desses valores informados"""

# Aula 01 - Exercício 03
valor1 = float(input("Informe o primeiro valor --> "))
valor2 = float(input("Informe o segundo valor diferente de zero --> "))

soma = valor1 + valor2
subtracao = valor1 - valor2
produto = valor1 * valor2
divisao = valor1 / valor2

print(f"A soma do primeiro valor com o segundo é: {soma}")
print(f"A diferença do primeiro valor com o segundo é: {subtracao}")
print(f"O produto do primeiro valor com o segundo é: {produto}")
print(f"A divisão do primeiro valor com o segundo é: {divisao}")