# -*- coding: utf-8 -*-
"""Aula1_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZtSfled783xolmj9ZnFqdqLUntbtQ6k

# Aula 01 - Exemplos

Versão simples
"""

# Aula 01 - Exemplos 01
nome = "João"       # variável do tipo str
idade = 25          # variável do tipo int
altura = 1.75       # variável do tipo float
estudante = True    # variável do tipo bool

print("Olá", nome)
print(f"Sua idade cadastrada é, {idade} anos.")
print(f"Foi informado que tem {altura} de altura e que é estudante.")
