# -*- coding: utf-8 -*-
"""Aula1_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZtSfled783xolmj9ZnFqdqLUntbtQ6k"""

# Aula 01 - Exercício 03
valor1 = float(input("Informe o primeiro valor --> "))
valor2 = float(input("Informe o segundo valor diferente de zero --> "))

soma = valor1 + valor2
subtracao = valor1 - valor2
produto = valor1 * valor2
divisao = valor1 / valor2

print(f"A soma do primeiro valor com o segundo é: {soma}")
print(f"A diferença do primeiro valor com o segundo é: {subtracao}")
print(f"O produto do primeiro valor com o segundo é: {produto}")
print(f"A divisão do primeiro valor com o segundo é: {divisao}")
