# -*- coding: utf-8 -*-
"""Aula1_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZtSfled783xolmj9ZnFqdqLUntbtQ6k
# Aula 01 - Exemplos 02"""

nome = input("Informe seu nome: ")       # variável do tipo str
idade = int(input("Informe sua idade: ")) # variável do tipo int
altura = float(input("Digite sua altura"))
estudante = bool(input("É estudante, digite True para sim")) # variável do tipo bool

print("Olá", nome)
print(f"Sua idade cadastrada é, {idade} anos.")
print(f"Foi informado que tem {altura} de altura e que é estudante.")
