# -*- coding: utf-8 -*-
"""Aula1_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZtSfled783xolmj9ZnFqdqLUntbtQ6k
    
# Aula 01 - Exercicio 02

Escreva um programa que leia o nome e a idade aluno. Peça três notas do aluno e exiba a média das notas
"""

# Aula 01 - Exercício 02
valor = float (input("Informe um valor númérico --> "))
dobro = valor *2
triplo = valor *3
raiz = valor **(1/2)
print(f"O valor informado foi {valor}")
print(f"O dobro do valor {valor} é {dobro}")
print(f"O triplo do valor {valor} é {triplo}")
print(f"A raiz quadrada do valor {valor} é {raiz}")
