# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""

# Aula 3 - While - Exemplo 03
contador = int(input("Digite um número interio para definir até qual valor será contado: "))
valor = int(input("Digite um número interio para informar onde inicia a contagem: "))
ranger = int(input("Digite um número interio para informar o passo da contagem: "))
while valor <= contador:
    print(valor)
    valor += ranger
