# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""

# Aula 3 - While - Exemplo 02
contador = int(input("Digite um número interio: "))
valor = 1
while valor <= contador:
    print(valor)
    valor += 1
