# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""

# Aula 3 - Controle de Laços: break - Exemplo 04
# A instrução break é usada para sair imediatamente de um loop quando uma condição específica é encontrada. A execução do programa continua na primeira instrução após o loop.
print("Exemplo com break:")
for i in range(1, 10):
  if i == 5:
    break # Sai do loop quando i for igual a 5
  print(i)
print("Loop encerrado.")
