# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""

# Aula 3 - Exercício 03 com WHILE
# Tabuada de um número até 10
print("Divisão de dois números")
dividendo = float(input("Digite o dividendo: "))
divisor = float(input("Digite o divisor: "))
while divisor == 0:
    print("Erro! O divisor não pode ser zero.")
    divisor = float(input("Digite o divisor novamente: "))
quociente = dividendo / divisor
print(f"O quociente da divisão é {quociente:.2f}")
