# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""

# Aula 3 - Exercício 03 com FOR
# Tabuada de um número até 10
valortabuada = int(input("Digite um número para gerar a tabuada: "))
print(f"Tabuada do {valortabuada}")
for i in range(1, 11):
    print(f"{valortabuada} x {i} = {valortabuada * i}")
