# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição

##While

###Exemplo 01
"""

# Aula 3 - While - Exemplo 01
x = 1
while x <= 5:
    print(x)
    x += 1

"""###Exemplo 02"""

# Aula 3 - While - Exemplo 02
contador = int(input("Digite um número interio: "))
valor = 1
while valor <= contador:
    print(valor)
    valor += 1

"""###Exemplo 04"""

# Aula 3 - While - Exemplo 03
contador = int(input("Digite um número interio para definir até qual valor será contado: "))
valor = int(input("Digite um número interio para informar onde inicia a contagem: "))
ranger = int(input("Digite um número interio para informar o passo da contagem: "))
while valor <= contador:
    print(valor)
    valor += ranger

"""##Laço for

###Exemplo 01
"""

# Aula 3 - FOR - Exemplo 01
for i in range(1, 6):
    print(i)

"""###Exemplo 02"""

# Aula 3 - FOR - Exemplo 02
for i in range(6):
    print(i)

"""###Exemplo 03"""

# Aula 3 - FOR - Exemplo 03
for i in range(6):
    if i == 5:
        break
    print(i)

"""###Exemplo 04"""

# Aula 3 - FOR - Exemplo 04
for i in range(1, 10):
  if i % 2 == 0: # Pula os números pares
    continue # Ignora o restante do código para números pares
  print(i)
print("Loop encerrado.")

"""# Exercícios

##1 - Imprima todos os números pares de 1 a 11

###Utilizando for
"""

# Aula 3 - Exercício 01 com FOR
# Imprima todos os números pares de 1 a 11
for i in range(1, 11):
    print(i)

"""###Utilizando while"""

# Aula 3 - Exercício 01 com WHILE
# Imprima todos os números pares de 1 a 11
i = 1
while i < 11:
  print(i)
  i = i + 1

"""##2 - Peça 10 números e calcule a soma

###Utilizando "FOR"
"""

# Aula 3 - Exercício 02 com FOR
# Peça 10 números e calcule a soma
total = 0
for i in range(1, 11):
    numero = float(input("Digite um valor numérico qualquer: "))
    print(f"O valor do {i}° número digitado foi {numero}")
    print()
    total = total + numero
print(f" A soma dos números informado é: {total}")

"""###Utilizando "WHILE"
"""

# Aula 3 - Exercício 02 com WHILE
# Peça 10 números e calcule a soma
soma = 0
i = 1
while i <= 10:
    numero = float(input("Digite um valor numérico qualquer: "))
    print(f"O valor do {i}° número digitado foi {numero}")
    soma = soma + numero
    i += 1
print(f"A soma dos valores digitados é {soma}")

"""##3 - Tabuada de um número até 10 usando for

###Utilizando "FOR"
"""

# Aula 3 - Exercício 03 com FOR
# Tabuada de um número até 10
valortabuada = int(input("Digite um número para gerar a tabuada: "))
print(f"Tabuada do {valortabuada}")
for i in range(1, 11):
    print(f"{valortabuada} x {i} = {valortabuada * i}")

"""##4 - Peça dois números ao usuário e divida o 1° pelo 2° número, caso o segundo seja zero, informe o usuário o erro, e peça para digitar novamente o segundo número.

###Utilizando "WHILE"
"""

# Aula 3 - Exercício 03 com WHILE
# Tabuada de um número até 10
print("Divisão de dois números")
dividendo = float(input("Digite o dividendo: "))
divisor = float(input("Digite o divisor: "))
while divisor == 0:
    print("Erro! O divisor não pode ser zero.")
    divisor = float(input("Digite o divisor novamente: "))
quociente = dividendo / divisor
print(f"O quociente da divisão é {quociente:.2f}")

"""# Controle de Laços: `break` e `continue`

Essas duas palavras-chave são usadas para alterar o fluxo de execução de um loop (`for` ou `while`).

### `break`

A instrução `break` é usada para **sair** imediatamente de um loop quando uma condição específica é encontrada. A execução do programa continua na primeira instrução após o loop.
"""

# Aula 3 - Controle de Laços: break - Exemplo 04
# A instrução break é usada para sair imediatamente de um loop quando uma condição específica é encontrada. A execução do programa continua na primeira instrução após o loop.
print("Exemplo com break:")
for i in range(1, 10):
  if i == 5:
    break # Sai do loop quando i for igual a 5
  print(i)
print("Loop encerrado.")

"""## continue

A instrução `continue` é usada para **pular** a iteração atual do loop e ir para a próxima iteração. O código restante dentro do loop para a iteração atual é ignorado.
"""

# Aula 3 - Controle de Laços: continue - Exemplo 05
# A instrução continue é usada para pular a iteração atual do loop e ir para a próxima iteração. O código restante dentro do loop para a iteração atual é ignorado.
print("\nExemplo com continue:")
for i in range(1, 10):
  if i % 2 == 0: # Pula os números pares
    continue # Ignora o restante do código para números pares
  print(i)
print("Loop encerrado.")

import random

numero_aleatorio = random.randint(0, 100)
print(numero_aleatorio)