# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""
# Aula 3 - Exercício 02 com WHILE
# Peça 10 números e calcule a soma
soma = 0
i = 1
while i <= 10:
    numero = float(input("Digite um valor numérico qualquer: "))
    print(f"O valor do {i}° número digitado foi {numero}")
    soma = soma + numero
    i += 1
print(f"A soma dos valores digitados é {soma}")
