# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""

# Aula 3 - Exercício 01 com FOR
# Imprima todos os números pares de 1 a 11
for i in range(1, 11):
    print(i)
