# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""

# Aula 3 - Controle de Laços - continue - Exemplo 05
# A instrução continue é usada para pular a iteração atual do loop e ir para a próxima iteração. O código restante dentro do loop para a iteração atual é ignorado.
print("\nExemplo com continue:")
for i in range(1, 10):
  if i % 2 == 0: # Pula os números pares
    continue # Ignora o restante do código para números pares
  print(i)
print("Loop encerrado.")
