# -*- coding: utf-8 -*-
"""Aula3_Sistema de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a44UAHjbpzJuBEn_b1U55e0srSdq9YJK

#Loop de repetição"""

# Aula 3 - Exercício 01 com WHILE
# Imprima todos os números pares de 1 a 11
i = 1
while i < 11:
  print(i)
  i = i + 1
