# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8

# Exemplo 01
"""

# Aula 5 - Exemplo 1
dados = [[1,2,3],
         [4,5,6],
         [7,8,9]]
print(dados)
print(dados[0])
print(dados[1])
print(dados[0][2])
print(dados[2][1])

"""#Exemplo 2

Notas

    Ana tem notas – 9, 10, 8
		Carlinhos tem notas – 10, 10, 5
		Caio tem notas – 10, 0, 5
"""

# Aula 5 - Exemplo 2
cadastro = ['Ana',
                [9,10,8],
            'Carlinhos',
                [10,10,5],
            'Caio',
                [10,0,5]]

cadastro[3][2] = 9
print(cadastro)
cadastro[5][1] = 10
print(cadastro)

"""#Exemplo 3

Exemplos 3 - Lista
"""

# Aula 5 - Exemplo 3
print('CADASTRO')
Cadastro = [['Adilson', [9,7,8,6]],
            ['Carlinhos', [8,7,6,10]],
            ['Matheus', [10,10,8,0]]]
for i in range(0,3):
  print(Cadastro[i])

"""#Exercicio 01 à 04

Exercicio 01

Crie uma matriz que armazene o nome de 5 pessoas,  idade, profissões.

	E uma estrutura “for” que imprima as informações da cada pessoa cadastrada.
"""

# Aula 5 - Exercício 1
# Crie uma matriz que armazene o nome de 5 pessoas, idade, profissões.
Cadastro = [['Carlinhos',17,'Vendedor'],
            ['Willian',41,'Tudo'],
            ['Adilson',54,'Enganobem'],
            ['João',18,'Jogador de Sinuca'],
            ['Claudio',23,'Soneca']]

for i in range(0,5):
  print(Cadastro[i])

"""Exercício 2 - Altere a idade da primeira pessoa para o dobro;

		A profissão da segunda para Eletricista;
		O nome do quarto para Laerte.

"""

# Aula 5 - Exercício 2
# Altere a idade da primeira pessoa para o dobro;
# A profissão da segunda para Eletricista;
# O nome do quarto para Laerte.
Cadastro[0][1] = Cadastro[0][1] *2
Cadastro[1][2] = 'Eletricista'
Cadastro[4][0] = 'Laerte'
for i in range(0,5):
  print(Cadastro[i])

"""Exercicio 3

"""

# Aula 5 - Exercício 3
# Inserir um dados novo
Cadastro.append(['Jorge',120,'Aposentado'])
quant = len(Cadastro)
for i in range(0,quant):
  print(Cadastro[i])

"""Exercicio 4

Crie uma lista chamada times, contendo 3 times de futebol.

Cada time deve ter uma lista com 3 jogadores.

Mostre na tela o nome do segundo jogador do primeiro time.

Inclua mais dois times com seus respectivos jogadores.

Mostre na tela a lista atualizada no formato de tabela.


"""

# Aula 5 - Exercício 4
# Crie uma lista chamada times, contendo 3 times de futebol.
# Cada time deve ter uma lista com 3 jogadores.
# Mostre na tela o nome do segundo jogador do primeiro time.
# Inclua mais dois times com seus respectivos jogadores.
# Mostre na tela a lista atualizada no formato de tabela.
Cadastro_Times = [['Corinthians',['Felix Torres','Hugo Souza','Mateuzinho']],
                  ['São Paulo',['Ferreirinha','Calleri','Luciano']],
                  ['Palmeiras',['Caslor Miguel','Paulinho','Raphael Veiga']]]
print(Cadastro_Times[0][1][1])
Cadastro_Times.append(['Santos',['Neymar','Gil Goiaba','Jão Paulo']])
Cadastro_Times.append(['Paysandu',['Matheus Nogueira','Lucas','Vilela']])
print(Cadastro_Times)
quant = len(Cadastro_Times)
for i in range(0,quant):
  print(Cadastro_Times[i])

"""# Exercicio 5

Crie um programa que:

    Solicite do usuário o nome de 3 alunos e suas 3 notas (por aluno);
    Armazene os dados em uma lista de listas;
    Calcule a média de cada aluno e mostre um “boletim” como abaixo;
"""

# Aula 5 - Exercício 5
#Crie um programa que:
# Solicite do usuário o nome de 3 alunos e suas 3 notas (por aluno);
# Armazene os dados em uma lista de listas;
# Calcule a média de cada aluno e mostre um “boletim” como abaixo;

# Listas criadas
Cadastro = []
cadastro_do_aluno = []
def Cadastro_Alunos():
    # Cadastro de alunos
    print('Cadastro de Alunos')
    for i in range(0,3):
      nome = input(f'\nInforme o {i+1}° aluno do cadastro: ')
      notas = []
      for j in range(0,3):
        nota = float(input(f'Informe a {j+1} nota do alunos: '))
        notas.append(nota)
      cadastro_do_aluno = [nome,notas]
      Cadastro.append(cadastro_do_aluno)
      print(f'Cadastro do aluno {nome} foi realizado com sucesso')

# Menu de opções
print('MENU DE OPÇÔES\n')
print('1 --> Cadastro de Alunos')
print('2 --> Impressão do Boletim')
print('3 --> sair do programa')
opcao = input('\nInforme a opção desejada')

# Analise da opção do usiário
if opcao == '1':
  Cadastro_Alunos()
elif opcao == '2':
  print('Boletim')
elif opcao == '3':
  print('Sair do programa')
else:
  print('Opção invalida')

"""#Exercicios 5 resolvido

Crie um programa que:

		Solicite do usuário o nome de 3 alunos e suas 3 notas (por aluno);
		Armazene os dados em uma lista de listas;
		Calcule a média de cada aluno e mostre um “boletim” como abaixo;
"""

# Aula 5 - Exercício 5
#Crie um programa que:
# Solicite do usuário o nome de 3 alunos e suas 3 notas (por aluno);
# Armazene os dados em uma lista de listas;
# Calcule a média de cada aluno e mostre um “boletim” como abaixo;

# Bibliotecas utilizadas
from IPython.core.display import clear_output

# Listas criadas
Cadastro = [['Adilson',[9.0,9.0,9.0],9.00],['João',[8.0,8.0,8.0],8.00],['Carlos',[7.0,7.0,7.0],7.00]]
cadastro_do_aluno = []

#Subprogramas criados

def cabecario(nometela): #Cabeçaria das telas de opções
    clear_output()
    print('#' * len(nometela))
    print(nometela)
    print('#' * len(nometela))
    print()

def Cadastro_Alunos(): # Cadastrar alunos
    cabecario('CADASTRO DE ALUNOS')
    for i in range(0,3):
      nome = input(f'\nInforme o {i+1}° aluno do cadastro: ')
      notas = []
      soma = 0
      for j in range(0,3):
        nota = float(input(f'Informe a {j+1} nota do alunos: '))
        soma = soma + nota
        notas.append(nota)
      media = soma / 3
      cadastro_do_aluno = [nome,notas,media]
      Cadastro.append(cadastro_do_aluno)
      print(f'Cadastro do aluno {nome} foi realizado com sucesso')
    retornoMenu()

def Menu(): # Menu de opções
    cabecario('MENU DE OPÇÔES')
    print('1 --> Cadastro de Alunos')
    print('2 --> Impressão do Boletim')
    print('3 --> sair do programa')
    opcao = input('\nInforme a opção desejada: \n')
    Menu_opcoes(opcao)

def sairprog(): # Sair do programa
    cabecario('SAIR DO PROGRAMA')
    print('\nDeseja realmente sair do programa')
    confirmacao = input('y - para sim   n - para não\n')
    if confirmacao == 'y' or confirmacao == 'Y':
        cabecario('SAIR DO PROGRAMA')
        print('\n Você saiu do programa')
    elif confirmacao == 'n' or confirmacao == 'N':
        Menu()
    else:
        opcaoinvalida()

def opcaoinvalida(): # O~pcão invalida do menu
    cabecario('OPÇÃO INVALIDA')
    retorno = input('\nDigite qual tecla para retornar ao menu principal: ')
    Menu()

def retornoMenu(): #Retornar para o menu
    retorno = input('\nDigite qual tecla para retornar ao menu principal: ')
    Menu()

def Menu_opcoes(opcao): # Analise da opção do usuário
    if opcao == '1':
      Cadastro_Alunos()
    elif opcao == '2':
      boletim(Cadastro)
    elif opcao == '3':
      sairprog()
    else:
      opcaoinvalida()

def boletim(cadastro): #Apresentar o boletim dos alunos
    cabecario('BOLETIM DE ALUNOS')
    print('-' * 45)
    print(f'|-{'Nome':<15}-|-{'Notas':<15}-|-{'Média':<5}-|')
    for k in range(0,len(cadastro)):
        nome = cadastro[k][0]
        notas = str(cadastro[k][1])
        media = (cadastro[k][2])
        print('-' * 45)
        print(f'|-{nome:<15}-|-{notas:<15}-|-{media:<5.2f}-|')
    print('-' * 45)
    retornoMenu()


# Programa Principal
Menu()

"""# Utilizado banco de dados em excel"""

# Aula 5 - Exercício 5 com excel
#Crie um programa que:
# Solicite do usuário o nome de 3 alunos e suas 3 notas (por aluno);
# Armazene os dados em uma lista de listas;
# Calcule a média de cada aluno e mostre um “boletim” como abaixo;

# BIBLIOTECAS CARREGADAS
from IPython.core.display import clear_output
import pandas as pd
#---------------------------------------

# LISTAS CRIADAS ------------------------
# Nome do arquivo Excel para armazenamento
EXCEL_FILE = 'cadastro_alunos.xlsx'

# Função para salvar a lista Cadastro em um arquivo Excel
def salvar_cadastro_excel(data_list):
    flat_data = []
    for aluno_data in data_list:
        name = aluno_data[0]
        notes = aluno_data[1]
        media = aluno_data[2]
        # Garante que sempre haja 3 notas para salvar no Excel
        n1 = notes[0] if len(notes) > 0 else None
        n2 = notes[1] if len(notes) > 1 else None
        n3 = notes[2] if len(notes) > 2 else None
        flat_data.append([name, n1, n2, n3, media])
    df = pd.DataFrame(flat_data, columns=['Nome', 'Nota1', 'Nota2', 'Nota3', 'Media'])
    df.to_excel(EXCEL_FILE, index=False)
    print(f"\nDados salvos em {EXCEL_FILE}")

# Função para carregar a lista Cadastro de um arquivo Excel
def carregar_cadastro_excel():
    try:
        df = pd.read_excel(EXCEL_FILE)
        loaded_cadastro = []
        for index, row in df.iterrows():
            name = row['Nome']
            # Converte as notas de volta para uma lista de floats
            notes = [row['Nota1'], row['Nota2'], row['Nota3']]
            notes = [float(n) for n in notes if pd.notna(n)] # Ignora valores NaN (vazios)
            media = float(row['Media'])
            loaded_cadastro.append([name, notes, media])
        print(f"\nDados carregados de {EXCEL_FILE}")
        return loaded_cadastro
    except FileNotFoundError:
        print(f"\nArquivo {EXCEL_FILE} não encontrado. Iniciando com dados padrão.")
        # Retorna dados padrão se o arquivo não for encontrado
        return [['Adilson',[9.0,9.0,9.0],9.0],
                ['Anderson',[8.0,8.0,8.0],8.0],
                ['Ana',[7.0,7.0,7.0],7.0]]
    except Exception as e:
        print(f"\nErro ao carregar dados do Excel ({e}). Iniciando com dados padrão.")
        # Retorna dados padrão em caso de outros erros de leitura
        return [['Adilson',[9.0,9.0,9.0],9.0],
                ['Anderson',[8.0,8.0,8.0],8.0],
                ['Ana',[7.0,7.0,7.0],7.0]]

# Inicializa a lista Cadastro carregando do Excel ou usando dados padrão
Cadastro = carregar_cadastro_excel()
cadastro_do_aluno = []
#-----------------------------------------

# SUB-PROGRAMAS CRIADOS ------------------
def Cadastro_Alunos(): # Cadastro de alunos
    cabecarioInicial('CADASTRO DE ALUNOS')
    for i in range(0,3):
      nome = input(f'\nInforme o {i+1}° aluno do cadastro: ')
      notas = []
      somaNota = 0
      for j in range(0,3):
        nota = float(input(f'Informe a {j+1} nota do aluno: '))
        somaNota = somaNota + nota
        notas.append(nota)
      mediaNota = somaNota/3
      cadastro_do_aluno = [nome,notas,mediaNota]
      Cadastro.append(cadastro_do_aluno)
    print(f'Cadastro de {nome} foi realizado com sucesso')
    salvar_cadastro_excel(Cadastro) # Salva as alterações no Excel
    retorn_Menu()

def menuinicial(): # Menu de opções informado
    cabecarioInicial('MENU DE OPÇÔES')
    print('1 --> Cadastro de Alunos')
    print('2 --> Impressão do Boletim')
    print('3 --> sair do programa')
    opcao = input('\nInforme a opção desejada\n')
    menuopcoes(opcao)

def menuopcoes(opcao): # Analise da opção do usuário
    if opcao == '1':
      Cadastro_Alunos()
    elif opcao == '2':
      prin_Boletim(Cadastro)
    elif opcao == '3':
      sair_Prog()
    else:
      opcao_Invalida()

def sair_Prog(): # Sair do programa
    cabecarioInicial('SAIR DO PROGRAMA')
    print('Deseja realmente sair do programa?')
    yorn = input('y -> para sim - n -> para não\n')
    if yorn == 'y' or yorn == 'Y':
      salvar_cadastro_excel(Cadastro) # Salva antes de sair
      clear_output()
      print('Você saiu do programa')
    elif yorn == 'n' or yorn == 'N':
      menuinicial()
    else:
      opcao_Invalida()

def opcao_Invalida(): # Para opção invalida
    cabecarioInicial('OPÇÃO INVALIDA')
    print('A opção selecionada é invalida')
    retorn_Menu()

def cabecarioInicial(mensagem): # Cabeçario inicial dos sub apresentado ao usuário
    clear_output()
    print(f'## {mensagem} ##\n')

def prin_Boletim(cadastro): # Apresentação do boletim
    cabecarioInicial('BOLETIM DE ALUNOS')
    print('-' * 51)
    print(f'|- {'ALUNO':<15} -|- {'NOTAS':<15} -|- {'MÉDIA':<5} -|')
    print('-' * 51)
    for k in range(0,len(cadastro)):
        notasdigitadas = str(cadastro[k][1])
        print(f'|- {cadastro[k][0]:<15} -|- {notasdigitadas:<14} -|- {cadastro[k][2]:<5.1f} -|')
        print('-' * 51)
    retorn_Menu()

def retorn_Menu(): # Verifica se deseja retornar ao menu
    retornoMenu = input('\nSelecione qualquer tecla para retornar ao Menu Principal\n')
    menuinicial()
#-------------------------------------------------------

# PROGRAMA PRINCIPAL --------------------------
menuinicial()