# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8
"""

# Aula 5 - Exemplo 1
dados = [[1,2,3],
         [4,5,6],
         [7,8,9]]
print(dados)
print(dados[0])
print(dados[1])
print(dados[0][2])
print(dados[2][1])
