# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8
"""

# Aula 5 - Exercício 4
# Crie uma lista chamada times, contendo 3 times de futebol.
# Cada time deve ter uma lista com 3 jogadores.
# Mostre na tela o nome do segundo jogador do primeiro time.
# Inclua mais dois times com seus respectivos jogadores.
# Mostre na tela a lista atualizada no formato de tabela.
Cadastro_Times = [['Corinthians',['Felix Torres','Hugo Souza','Mateuzinho']],
                  ['São Paulo',['Ferreirinha','Calleri','Luciano']],
                  ['Palmeiras',['Caslor Miguel','Paulinho','Raphael Veiga']]]
print(Cadastro_Times[0][1][1])
Cadastro_Times.append(['Santos',['Neymar','Gil Goiaba','Jão Paulo']])
Cadastro_Times.append(['Paysandu',['Matheus Nogueira','Lucas','Vilela']])
print(Cadastro_Times)
quant = len(Cadastro_Times)
for i in range(0,quant):
  print(Cadastro_Times[i])
