# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8
"""

# Aula 5 - Exercício 5
#Crie um programa que:
# Solicite do usuário o nome de 3 alunos e suas 3 notas (por aluno);
# Armazene os dados em uma lista de listas;
# Calcule a média de cada aluno e mostre um “boletim” como abaixo;
#----------------------------------------------------------------------

# Bibliotecas utilizadas
from IPython.core.display import clear_output
from datetime import datetime
#----------------------------------------------------------------------

# Listas criadas
Cadastro = [['Adilson',[9.0,9.0,9.0],9.00],['João',[8.0,8.0,8.0],8.00],['Carlos',[7.0,7.0,7.0],7.00]]
cadastro_do_aluno = []
#----------------------------------------------------------------------

#Subprogramas criados

def cabecario(nometela): #Cabeçaria das telas de opções
    clear_output()
    time = datetime.now()
    hora = time.hour
    if hora < 12:
      periodo = "Bom dia!"
    elif hora < 18:
      periodo = "Boa tarde!"
    else:
      periodo = "Boa noite!"
    print('#' * (len(nometela) + len(periodo) + 7))
    print(f'# {nometela} # {periodo} #')
    print('#' * (len(nometela) + len(periodo) + 7))
    print(f"Agora são {time.strftime('%H:%M:%S')}")
    print()

def Cadastro_Alunos(): # Cadastrar alunos
    cabecario('CADASTRO DE ALUNOS')
    for i in range(0,3):
      nome = input(f'\nInforme o {i+1}° aluno do cadastro: ')
      notas = []
      soma = 0
      for j in range(0,3):
        nota = float(input(f'Informe a {j+1} nota do alunos: '))
        soma = soma + nota
        notas.append(nota)
      media = soma / 3
      cadastro_do_aluno = [nome,notas,media]
      Cadastro.append(cadastro_do_aluno)
      print(f'Cadastro do aluno {nome} foi realizado com sucesso')
    retornoMenu()

def Menu(): # Menu de opções
    cabecario('MENU DE OPÇÔES')
    print('1 --> Cadastro de Alunos')
    print('2 --> Impressão do Boletim')
    print('3 --> sair do programa')
    opcao = input('\nInforme a opção desejada: \n')
    Menu_opcoes(opcao)

def sairprog(): # Sair do programa
    cabecario('SAIR DO PROGRAMA')
    print('\nDeseja realmente sair do programa')
    confirmacao = input('y - para sim   n - para não\n')
    if confirmacao == 'y' or confirmacao == 'Y':
        cabecario('SAIR DO PROGRAMA')
        print('\n Você saiu do programa')
    elif confirmacao == 'n' or confirmacao == 'N':
        Menu()
    else:
        opcaoinvalida()

def opcaoinvalida(): # O~pcão invalida do menu
    cabecario('OPÇÃO INVALIDA')
    retorno = input('\nDigite qual tecla para retornar ao menu principal: ')
    Menu()

def retornoMenu(): #Retornar para o menu
    retorno = input('\nDigite qual tecla para retornar ao menu principal: ')
    Menu()

def Menu_opcoes(opcao): # Analise da opção do usuário
    if opcao == '1':
      Cadastro_Alunos()
    elif opcao == '2':
      boletim(Cadastro)
    elif opcao == '3':
      sairprog()
    else:
      opcaoinvalida()

def boletim(cadastro): #Apresentar o boletim dos alunos
    cabecario('BOLETIM DE ALUNOS')
    print('-' * 45)
    print(f'|-{'Nome':<15}-|-{'Notas':<15}-|-{'Média':<5}-|')
    for k in range(0,len(cadastro)):
        nome = cadastro[k][0]
        notas = str(cadastro[k][1])
        media = (cadastro[k][2])
        print('-' * 45)
        print(f'|-{nome:<15}-|-{notas:<15}-|-{media:<5.2f}-|')
    print('-' * 45)
    retornoMenu()
#----------------------------------------------------------------------

# Programa Principal
Menu()
