# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8
"""

# Aula 5 - Exercício 5 com excel
#Crie um programa que:
# Solicite do usuário o nome de 3 alunos e suas 3 notas (por aluno);
# Armazene os dados em uma lista de listas;
# Calcule a média de cada aluno e mostre um “boletim” como abaixo;
# Utilizado banco de dados em Excel

# BIBLIOTECAS CARREGADAS
from IPython.core.display import clear_output
import pandas as pd
from datetime import datetime
#---------------------------------------

# LISTAS CRIADAS ------------------------
# Nome do arquivo Excel para armazenamento
EXCEL_FILE = 'cadastro_alunos.xlsx'

# Função para salvar a lista Cadastro em um arquivo Excel
def salvar_cadastro_excel(data_list):
    flat_data = []
    for aluno_data in data_list:
        name = aluno_data[0]
        notes = aluno_data[1]
        media = aluno_data[2]
        # Garante que sempre haja 3 notas para salvar no Excel
        n1 = notes[0] if len(notes) > 0 else None
        n2 = notes[1] if len(notes) > 1 else None
        n3 = notes[2] if len(notes) > 2 else None
        flat_data.append([name, n1, n2, n3, media])
    df = pd.DataFrame(flat_data, columns=['Nome', 'Nota1', 'Nota2', 'Nota3', 'Media'])
    df.to_excel(EXCEL_FILE, index=False)
    print(f"\nDados salvos em {EXCEL_FILE}")

# Função para carregar a lista Cadastro de um arquivo Excel
def carregar_cadastro_excel():
    try:
        df = pd.read_excel(EXCEL_FILE)
        loaded_cadastro = []
        for index, row in df.iterrows():
            name = row['Nome']
            # Converte as notas de volta para uma lista de floats
            notes = [row['Nota1'], row['Nota2'], row['Nota3']]
            notes = [float(n) for n in notes if pd.notna(n)] # Ignora valores NaN (vazios)
            media = float(row['Media'])
            loaded_cadastro.append([name, notes, media])
        print(f"\nDados carregados de {EXCEL_FILE}")
        return loaded_cadastro
    except FileNotFoundError:
        print(f"\nArquivo {EXCEL_FILE} não encontrado. Iniciando com dados padrão.")
        # Retorna dados padrão se o arquivo não for encontrado
        return [['Adilson',[9.0,9.0,9.0],9.0],
                ['Anderson',[8.0,8.0,8.0],8.0],
                ['Ana',[7.0,7.0,7.0],7.0]]
    except Exception as e:
        print(f"\nErro ao carregar dados do Excel ({e}). Iniciando com dados padrão.")
        # Retorna dados padrão em caso de outros erros de leitura
        return [['Adilson',[9.0,9.0,9.0],9.0],
                ['Anderson',[8.0,8.0,8.0],8.0],
                ['Ana',[7.0,7.0,7.0],7.0]]

# Inicializa a lista Cadastro carregando do Excel ou usando dados padrão
Cadastro = carregar_cadastro_excel()
cadastro_do_aluno = []
#-----------------------------------------

# SUB-PROGRAMAS CRIADOS ------------------
def Cadastro_Alunos(): # Cadastro de alunos
    cabecarioInicial('CADASTRO DE ALUNOS')
    for i in range(0,3):
      nome = input(f'\nInforme o {i+1}° aluno do cadastro: ')
      notas = []
      somaNota = 0
      for j in range(0,3):
        nota = float(input(f'Informe a {j+1} nota do aluno: '))
        somaNota = somaNota + nota
        notas.append(nota)
      mediaNota = somaNota/3
      cadastro_do_aluno = [nome,notas,mediaNota]
      Cadastro.append(cadastro_do_aluno)
    print(f'Cadastro de {nome} foi realizado com sucesso')
    salvar_cadastro_excel(Cadastro) # Salva as alterações no Excel
    retorn_Menu()

def menuinicial(): # Menu de opções informado
    cabecarioInicial('MENU DE OPÇÔES')
    print('1 --> Cadastro de Alunos')
    print('2 --> Impressão do Boletim')
    print('3 --> sair do programa')
    opcao = input('\nInforme a opção desejada\n')
    menuopcoes(opcao)

def menuopcoes(opcao): # Analise da opção do usuário
    if opcao == '1':
      Cadastro_Alunos()
    elif opcao == '2':
      prin_Boletim(Cadastro)
    elif opcao == '3':
      sair_Prog()
    else:
      opcao_Invalida()

def sair_Prog(): # Sair do programa
    cabecarioInicial('SAIR DO PROGRAMA')
    print('Deseja realmente sair do programa?')
    yorn = input('y -> para sim - n -> para não\n')
    if yorn == 'y' or yorn == 'Y':
      salvar_cadastro_excel(Cadastro) # Salva antes de sair
      clear_output()
      print('Você saiu do programa')
    elif yorn == 'n' or yorn == 'N':
      menuinicial()
    else:
      opcao_Invalida()

def opcao_Invalida(): # Para opção invalida
    cabecarioInicial('OPÇÃO INVALIDA')
    print('A opção selecionada é invalida')
    retorn_Menu()

def cabecarioInicial(mensagem): # Cabeçario inicial dos sub apresentado ao usuário
    clear_output()
    time = datetime.now()
    hora = time.hour
    if hora < 12:
      periodo = "Bom dia!"
    elif hora < 18:
      periodo = "Boa tarde!"
    else:
      periodo = "Boa noite!"
    print('#' * (len(mensagem) + len(periodo) + 7))
    print(f'# {mensagem} # {periodo} #')
    print('#' * (len(mensagem) + len(periodo) + 7))
    print(f"Agora são {time.strftime('%H:%M:%S')}")
    print()

def prin_Boletim(cadastro): # Apresentação do boletim
    cabecarioInicial('BOLETIM DE ALUNOS')
    print('-' * 51)
    print(f'|- {'ALUNO':<15} -|- {'NOTAS':<15} -|- {'MÉDIA':<5} -|')
    print('-' * 51)
    for k in range(0,len(cadastro)):
        notasdigitadas = str(cadastro[k][1])
        print(f'|- {cadastro[k][0]:<15} -|- {notasdigitadas:<14} -|- {cadastro[k][2]:<5.1f} -|')
        print('-' * 51)
    retorn_Menu()

def retorn_Menu(): # Verifica se deseja retornar ao menu
    retornoMenu = input('\nSelecione qualquer tecla para retornar ao Menu Principal\n')
    menuinicial()
#-------------------------------------------------------

# PROGRAMA PRINCIPAL --------------------------
menuinicial()
