# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8
"""

# Aula 5 - Exemplo 2
cadastro = ['Ana',
                [9,10,8],
            'Carlinhos',
                [10,10,5],
            'Caio',
                [10,0,5]]

cadastro[3][2] = 9
print(cadastro)
cadastro[5][1] = 10
print(cadastro)
