# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8
"""

# Aula 5 - Exemplo 3
print('CADASTRO')
Cadastro = [['Adilson', [9,7,8,6]],
            ['Carlinhos', [8,7,6,10]],
            ['Matheus', [10,10,8,0]]]
for i in range(0,3):
  print(Cadastro[i])
