# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8
"""

# Aula 5 - Exercício 1
# Crie uma matriz que armazene o nome de 5 pessoas, idade, profissões.
Cadastro = [['Carlinhos',17,'Vendedor'],
            ['Willian',41,'Tudo'],
            ['Adilson',54,'Enganobem'],
            ['João',18,'Jogador de Sinuca'],
            ['Claudio',23,'Soneca']]

for i in range(0,5):
  print(Cadastro[i])
