# -*- coding: utf-8 -*-
"""Aula 5.1_Matriz_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHy5EmR5uSXidfDRoFj7kT1H02XI2KL8
"""

# Aula 5 - Exercício 1
# Altere a idade da primeira pessoa para o dobro;
# A profissão da segunda para Eletricista;
# O nome do quarto para Laerte.
Cadastro[0][1] = Cadastro[0][1] *2
Cadastro[1][2] = 'Eletricista'
Cadastro[4][0] = 'Laerte'
for i in range(0,5):
  print(Cadastro[i])
