# -*- coding: utf-8 -*-
"""Aula2_Exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mj7mAs0QA7de_0m1DUUgoLp3Js63YHk

#Tomada de decisões com if, elif, e else.
"""
t(input("Informe um ano qualquer: "))
# % traz o valor do resto de uma divisão
if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
    print(f"O ano {ano} é bissexto")
else:
    print(f"O ano {ano} não é bissexto")
