# -*- coding: utf-8 -*-
"""Aula2_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mj7mAs0QA7de_0m1DUUgoLp3Js63YHk

#Tomada de decisões com if, elif, e else.

##Condição Aninhada
"""

# Aula 2 - Exemplo 03 - Estrutura condicional aninhada
valor1 = float(input("Informe um valor qualquer: "))
valor2 = float(input("Informe outro valor qualquer: "))

if valor1 > valor2:
    print(f"O primeiro valor {valor1} é maior que o segundo {valor2}")
else:
  if valor1 < valor2:
    print(f"O primeiro valor {valor1} é menor que o segundo {valor2}")
  else:
    if valor1 == valor2:
      print(f"O primeiro valor {valor1} é igual ao segundo {valor2}")
    else:
      if valor1 != valor2:
        print(f"O primeiro valor {valor1} é diferente do segundo {valor2}")
