# -*- coding: utf-8 -*-
"""Aula2_Exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mj7mAs0QA7de_0m1DUUgoLp3Js63YHk

#Tomada de decisões com if, elif, e else.

"""# Exercícios

##01 - Verifique se um número é positivo, negativo ou zero"""

# Aula 2 - Exercício 01
# Verifique se um número é positivo, negativo ou zero
valor = float(input("Informe um valor qualquer: "))

if valor > 0:
    print(f"O valor {valor} é positivo")
elif valor < 0:
    print(f"O valor {valor} é negativo")
else:
    print(f"O valor é igual a {valor}")
