# -*- coding: utf-8 -*-
"""Aula2_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mj7mAs0QA7de_0m1DUUgoLp3Js63YHk

#Tomada de decisões com if, elif, e else.

"""# Exercícios

"""##04 - Crie uma calculadora que escolha a operação com base em uma opção digitada e realize a operação escolhida, por dois números informados pelo usuário"""

# Aula 2 - Exercício 04
# Crie uma calculadora que escolha a operação com base em uma opção digitada
# e realize a operação escolhida, por dois números informados pelo usuário
print("Seja bem vindo a esta calculadora de dois números")
valor1 = float(input("Informe o primeiro valor --> "))
valor2 = float(input("Informe o segundo valor --> "))
print("Informe a operação que deseja realizar")
print("1 - Adição")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")
opcao = int(input("Informe a opção desejada --> "))

if opcao == 1:
    soma = valor1 + valor2
    print(f"A soma dos valores {valor1} e {valor2} é {soma}")
elif opcao == 2:
    subtracao = valor1 - valor2
    print(f"A subtração dos valores {valor1} e {valor2} é {subtracao}")
elif opcao == 3:
    multiplicacao = valor1 * valor2
    print(f"A multiplicação dos valores {valor1} e {valor2} é {multiplicacao}")
elif opcao == 4:
    divisao = valor1 / valor2
    print(f"A divisão dos valores {valor1} e {valor2} é {divisao}")
else:
    print("Opção inválida")
