# -*- coding: utf-8 -*-
"""Aula2_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mj7mAs0QA7de_0m1DUUgoLp3Js63YHk

#Tomada de decisões com if, elif, e else.

"""# Exercícios

"""##03 - Peça três números e diga qual é o maior"""

# Aula 2 - Exercício 03
# Peça três números e diga qual é o maior
print("Informe três números diferentes")
numero1 = float(input("Informe o primeiro número --> "))
numero2 = float(input("Informe o segundo número --> "))
numero3 = float(input("Informe o terceiro número --> "))

if numero1 > numero2 and numero1 > numero3:
    print(f"O primeiro número {numero1} é o maior")
elif numero2 > numero1 and numero2 > numero3:
    print(f"O segundo número {numero2} é o maior")
else:
    print(f"O terceiro número {numero3} é o maior")
