# -*- coding: utf-8 -*-
"""Aula2_Exemplos_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mj7mAs0QA7de_0m1DUUgoLp3Js63YHk

#Tomada de decisões com if, elif, e else.

##Condição simples
"""

# Aula 2 - Exemplo 01 - Condição simples
valor1 = float(input("Informe um valor qualquer: "))
valor2 = float(input("Informe outro valor qualquer: "))

if valor1 > valor2:
    print(f"O primeiro valor {valor1} é maior que o segundo {valor2}")
if valor1 < valor2:
    print(f"O primeiro valor {valor1} é menor que o segundo {valor2}")
if valor1 == valor2:
    print(f"O primeiro valor {valor1} é igual ao segundo {valor2}")
if valor1 != valor2:
    print(f"O primeiro valor {valor1} é diferente do segundo {valor2}")

"""##Condição composta"""

# Aula 2 - Exemplo 02 - Condição composta
valor1 = float(input("Informe um valor qualquer: "))
valor2 = float(input("Informe outro valor diferente do anterior: "))

if valor1 > valor2:
    print(f"O primeiro valor {valor1} é maior que o segundo {valor2}")
else:
    print(f"O primeiro valor {valor1} é menor que o segundo {valor2}")

"""##Estrutura condicional aninhada"""

# Aula 2 - Exemplo 03 - Estrutura condicional aninhada
valor1 = float(input("Informe um valor qualquer: "))
valor2 = float(input("Informe outro valor qualquer: "))

if valor1 > valor2:
    print(f"O primeiro valor {valor1} é maior que o segundo {valor2}")
else:
  if valor1 < valor2:
    print(f"O primeiro valor {valor1} é menor que o segundo {valor2}")
  else:
    if valor1 == valor2:
      print(f"O primeiro valor {valor1} é igual ao segundo {valor2}")
    else:
      if valor1 != valor2:
        print(f"O primeiro valor {valor1} é diferente do segundo {valor2}")

"""##Estrutura condicional de múltiplas condições"""

# Aula 2 - Exemplo 04 - Estrutura condicional de múltiplas condições
valor1 = float(input("Informe um valor qualquer: "))
valor2 = float(input("Informe outro valor qualquer: "))

if valor1 > valor2:
    print(f"O primeiro valor {valor1} é maior que o segundo {valor2}")
    print(f"O primeiro valor {valor1} é diferente do segundo {valor2}")
elif valor1 < valor2:
    print(f"O primeiro valor {valor1} é menor que o segundo {valor2}")
    print(f"O primeiro valor {valor1} é diferente do segundo {valor2}")
elif valor1 == valor2:
      print(f"O primeiro valor {valor1} é igual ao segundo {valor2}")

"""# Exercícios

##01 - Verifique se um número é positivo, negativo ou zero
"""

# Aula 2 - Exercício 01
# Verifique se um número é positivo, negativo ou zero
valor = float(input("Informe um valor qualquer: "))

if valor > 0:
    print(f"O valor {valor} é positivo")
elif valor < 0:
    print(f"O valor {valor} é negativo")
else:
    print(f"O valor é igual a {valor}")

"""##02 - Verificação simples se um ano é bissexto"""

# Aula 2 - Exercício 02
# Verificação simples se um ano é bissexto
ano = int(input("Informe um ano qualquer: "))
# % traz o valor do resto de uma divisão
if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
    print(f"O ano {ano} é bissexto")
else:
    print(f"O ano {ano} não é bissexto")

"""##03 - Peça três números e diga qual é o maior"""

# Aula 2 - Exercício 03
# Peça três números e diga qual é o maior
print("Informe três números diferentes")
numero1 = float(input("Informe o primeiro número --> "))
numero2 = float(input("Informe o segundo número --> "))
numero3 = float(input("Informe o terceiro número --> "))

if numero1 > numero2 and numero1 > numero3:
    print(f"O primeiro número {numero1} é o maior")
elif numero2 > numero1 and numero2 > numero3:
    print(f"O segundo número {numero2} é o maior")
else:
    print(f"O terceiro número {numero3} é o maior")

"""##04 - Crie uma calculadora que escolha a operação com base em uma opção digitada e realize a operação escolhida, por dois números informados pelo usuário"""

# Aula 2 - Exercício 04
# Crie uma calculadora que escolha a operação com base em uma opção digitada
# e realize a operação escolhida, por dois números informados pelo usuário
print("Seja bem vindo a esta calculadora de dois números")
valor1 = float(input("Informe o primeiro valor --> "))
valor2 = float(input("Informe o segundo valor --> "))
print("Informe a operação que deseja realizar")
print("1 - Adição")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")
opcao = int(input("Informe a opção desejada --> "))

if opcao == 1:
    soma = valor1 + valor2
    print(f"A soma dos valores {valor1} e {valor2} é {soma}")
elif opcao == 2:
    subtracao = valor1 - valor2
    print(f"A subtração dos valores {valor1} e {valor2} é {subtracao}")
elif opcao == 3:
    multiplicacao = valor1 * valor2
    print(f"A multiplicação dos valores {valor1} e {valor2} é {multiplicacao}")
elif opcao == 4:
    divisao = valor1 / valor2
    print(f"A divisão dos valores {valor1} e {valor2} é {divisao}")
else:
    print("Opção inválida")