# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""

# Aula 4 - Funções e Modularização - Example 7
# Example 7: Uma função recursiva para calcular fatorial
def factorial(n):
  #"""Calcula o fatorial de um inteiro não negativo usando recursão."""
  if n == 0:
    return 1
  else:
    # n * facturial(n-1) --> é uma função para calcular
    return n * factorial(n-1)

# Utilizando a function
num = int(input("Informe um número inteiro não negativo: "))
print(f"O fatorial de {num} é: {factorial(num)}")
