# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""
# Aula 4 - Funções e Modularização - Example 2
# function que verifica se um número é primo
def e_prime(number):
  #"""Verifica se um número é primo."""

  if number % 2 == 0:
    return True
  else:
    return False

# Utilizando a function
num1 = int(input("Informe um número inteiro: "))
num2 = int(input("Informe outro número inteiro: "))
print(f"{num1} é primo? -  {e_prime(num1)}")
print(f"{num2} é primo? -  {e_prime(num2)}")
