# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""

# Aula 4 - Funções e Modularização - Exercício 5
# Utilização de "reverse"
def ListaInvert(Lista_Origem):
    Lista_Origem.reverse()
    return Lista_Origem

# Lista original
Lista = [1, 2, 3, 4, 5]

# Imprimindo a lista
print("Lista inicial")
print(Lista)

# Chamando a função
Lista_Invertida = ListaInvert(Lista)

# Imprimindo a lista invertida
print("Lista invertida")
print(Lista_Invertida)
print(Lista)
