# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""

# Aula 4 - Funções e Modularização - Exercício 3
# Função que receba uma lista de notas e retorne a média

def NotaMedia(notas, contador):
  #"""Calcula a média de uma lista de notas."""
  total = sum(notas)
  media = total / contador
  return media

lista_notas = [] # função para criar uma lista
contador = 0
resp = 1

while resp == 1:
    contador += 1
    nota = float(input(f"Informe a {contador}ª nota: "))
    lista_notas.append(nota)  # Adiciona a nota na lista
    print("Deseja informar mais uma nota?")
    resp = int(input("Opção: 1 --> Sim  -  2 --> Não "))
    while resp <> 1 or resp <> 2:
      print("Opção inválida")
      resp = int(input("Opção: 1 --> Para Sim  -  2 --> Para Não "))


media = NotaMedia(lista_notas, contador)
print(f"A média das notas é {media:.2f}")
