# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""

# Aula 4 - Funções e Modularização - Exercício 1
# function que verifica se um número é par ou impar
def Par_Impar(numero):
  #"""Verifica se par ou impar."""
  n = float(numero % 2)
  print(f"O resto da divisão do número {num} por 2 é: {n:.0f}, portando:") # :.0f define a quantidade de casas após virgula no caso nenhuma casa
  if n == 0:
    return True
  else:
    return False

# Utilizando a function
num = int(input("Informe um número inteiro: "))
if Par_Impar(num) == True:
  print(f"O número {num} é par")
else:
  print(f"O número {num} é impar")
