# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""

# Aula 4 - Funções e Modularização - Example 6
#O **kwargs no Python é uma forma de passar um número variável de argumentos de
#palavra-chave para uma função. Ele coleta todos os argumentos de palavra-chave
# que não correspondem a um parâmetro formal em um dicionário.
# No Examplo 6, a função display_info usa **kwargs para aceitar qualquer número
# de argumentos de palavra-chave, como nome, idade e cidade. Dentro da função,
# esses argumentos são armazenados em um dicionário chamado kwargs, onde as chaves
# são os nomes dos argumentos de palavra-chave e os valores são os valores correspondentes.
# O loop for então itera sobre este dicionário e imprime cada par chave-valor.
def exibir_informacoes(**kwargs):
  #"""Exibe informações fornecidas como argumentos de palavras-chave."""
  for chave, valor in kwargs.items():
    print(f"{chave}: {valor}")

# Utilizando a function
exibir_informacoes(nome="Arthur", idade=30, cidade="São Bernardo")
