# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""

# Aula 4 - Funções e Modularização - Example 5
# Uma function que aceita um número variável de argumentos
def sum_all(*args):
  #"""Calcula a soma de todos os argumentos fornecidos."""
  total = 0
  for num in args:
    total += num
  return total

# Utilizando a function
print(f"Soma de 1, 2, 3 é: {sum_all(1, 2, 3)}")
print(f"Soma de 10, 20, 30, 40, 50 é: {sum_all(10, 20, 30, 40, 50)}")
