# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""
# Aula 4 - Funções e Modularização - Example 3
# Uma function que inverte uma variável do tipo texto
def reverse_string(input_string):
  #"""Inverte uma string fornecida."""
  return input_string[::-1]

# Using the function
text = "Hello, World!"
reversed_text = reverse_string(text)
print(f"Texto original: {text}")
print(f"Texto invertido: {reversed_text}")
