# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização

##Example 1: function para calcular área do retângulo
"""

# Aula 4 - Funções e Modularização - Example 1
# function para calcular área do retângulo
def calculate_rectangle_area(comprimento, largura):
  area = comprimento * largura
  print(area)
  return area

# Utilizando a função "def"
medida1 = float(input("Informe o valor do comprimento do retângulo: "))
medida2 = float(input("Informe o valor da largura do retângulo: "))
outro = calculate_rectangle_area(medida1, medida2)
print(outro)
print(f"A área do reângulo de {medida1} e largura {medida2} é: {calculate_rectangle_area(medida1, medida2)}")

"""##Example 2: function que verifica se um número é primo"""

# Aula 4 - Funções e Modularização - Example 2
# function que verifica se um número é primo
def e_prime(number):
  #"""Verifica se um número é primo."""

  if number % 2 == 0:
    return True
  else:
    return False

# Utilizando a function
num1 = int(input("Informe um número inteiro: "))
num2 = int(input("Informe outro número inteiro: "))
print(f"{num1} é primo? -  {e_prime(num1)}")
print(f"{num2} é primo? -  {e_prime(num2)}")

"""##Example 3: Uma function que inverte uma variável do tipo texto"""

# Aula 4 - Funções e Modularização - Example 3
# Uma function que inverte uma variável do tipo texto
def reverse_string(input_string):
  #"""Inverte uma string fornecida."""
  return input_string[::-1]

# Using the function
text = "Hello, World!"
reversed_text = reverse_string(text)
print(f"Texto original: {text}")
print(f"Texto invertido: {reversed_text}")

"""##Example 4: Uma function com argumentos padrão"""

# Aula 4 - Funções e Modularização - Example 4
# Uma function com argumentos padrão
def saudacao(nome="Convidado (a)", saudacao="Olá"):
  #"""Cumprimenta uma pessoa com uma saudação e um nome opcionais."""
  print(f"{saudacao}, {nome}!")

# Utilizando a function
saudacao()  # Usa argumentos padrão
saudacao("Alice") # Usa saudação padrão
saudacao("Rocha", "Bom dia") # Fornece ambos os argumentos

"""##Example 5: Uma function que aceita um número variável de argumentos"""

# Aula 4 - Funções e Modularização - Example 5
# Uma function que aceita um número variável de argumentos
def sum_all(*args):
  #"""Calcula a soma de todos os argumentos fornecidos."""
  total = 0
  for num in args:
    total += num
  return total

# Utilizando a function
print(f"Soma de 1, 2, 3 é: {sum_all(1, 2, 3)}")
print(f"Soma de 10, 20, 30, 40, 50 é: {sum_all(10, 20, 30, 40, 50)}")

"""##Examplo 6: Uma função que aceita um número variável de argumentos de palavras-chave"""

# Aula 4 - Funções e Modularização - Example 6
#O **kwargs no Python é uma forma de passar um número variável de argumentos de
#palavra-chave para uma função. Ele coleta todos os argumentos de palavra-chave
# que não correspondem a um parâmetro formal em um dicionário.
# No Examplo 6, a função display_info usa **kwargs para aceitar qualquer número
# de argumentos de palavra-chave, como nome, idade e cidade. Dentro da função,
# esses argumentos são armazenados em um dicionário chamado kwargs, onde as chaves
# são os nomes dos argumentos de palavra-chave e os valores são os valores correspondentes.
# O loop for então itera sobre este dicionário e imprime cada par chave-valor.
def exibir_informacoes(**kwargs):
  #"""Exibe informações fornecidas como argumentos de palavras-chave."""
  for chave, valor in kwargs.items():
    print(f"{chave}: {valor}")

# Utilizando a function
exibir_informacoes(nome="Arthur", idade=30, cidade="São Bernardo")

"""##Example 7: Uma função recursiva para calcular fatorial"""

# Aula 4 - Funções e Modularização - Example 7
# Example 7: Uma função recursiva para calcular fatorial
def factorial(n):
  #"""Calcula o fatorial de um inteiro não negativo usando recursão."""
  if n == 0:
    return 1
  else:
    # n * facturial(n-1) --> é uma função para calcular
    return n * factorial(n-1)

# Utilizando a function
num = int(input("Informe um número inteiro não negativo: "))
print(f"O fatorial de {num} é: {factorial(num)}")

"""# Solução para os exercícios

##Exercício 1 - function que verifica se um número é par ou impar
"""

# Aula 4 - Funções e Modularização - Exercício 1
# function que verifica se um número é par ou impar
def Par_Impar(numero):
  #"""Verifica se par ou impar."""
  n = float(numero % 2)
  print(f"O resto da divisão do número {num} por 2 é: {n:.0f}, portando:") # :.0f define a quantidade de casas após virgula no caso nenhuma casa
  if n == 0:
    return True
  else:
    return False

# Utilizando a function
num = int(input("Informe um número inteiro: "))
if Par_Impar(num) == True:
  print(f"O número {num} é par")
else:
  print(f"O número {num} é impar")

"""##Exercício 2 - Função que verifique se um número é primo."""

# Aula 4 - Funções e Modularização - Exercício 2
# Função que verifique se um número é primo.
def Num_Primo(numero):
  for i in range(2, numero):
    if numero % i == 0:
      return False
  return True

numPrimo = int(input("Informe um número inteiro: "))
if Num_Primo(numPrimo):
  print(f"O número {numPrimo} é primo")
else:
  print(f"O número {numPrimo} não é primo")

"""##Exercício 3 - Função que receba uma lista de notas e retorne a média"""

# Aula 4 - Funções e Modularização - Exercício 3
# Função que receba uma lista de notas e retorne a média

def NotaMedia(notas, contador):
  #"""Calcula a média de uma lista de notas."""
  total = sum(notas)
  media = total / contador
  return media

lista_notas = [] # função para criar uma lista
contador = 0
resp = 1

while resp == 1:
    contador += 1
    nota = float(input(f"Informe a {contador}ª nota: "))
    lista_notas.append(nota)  # Adiciona a nota na lista
    print("Deseja informar mais uma nota?")
    resp = int(input("Opção: 1 --> Sim  -  2 --> Não "))
    while resp <> 1 or resp <> 2:
      print("Opção inválida")
      resp = int(input("Opção: 1 --> Para Sim  -  2 --> Para Não "))


media = NotaMedia(lista_notas, contador)
print(f"A média das notas é {media:.2f}")

"""##Exercício 4 - Data a lista abaixo, inverta a ordem dos números.

	Lista_Origem = [1, 2, 4, 5]
"""

# Aula 4 - Funções e Modularização - Exercício 4
# Data a lista abaixo, inverta a ordem dos números.
def ListaInvert(Lista_Origem):
  Lista_Inverte = Lista_Origem [::-1]
  return Lista_Inverte

# Lista original
Lista = [1, 2, 3, 4, 5]

# Chamando a função
Lista_Final = ListaInvert(Lista)

# Imprimindo as listas
print("Lista inicial")
print(Lista)
print("Lista invertida")
print(Lista_Final)

"""##Exercício 5 - Utilização de "reverse"
"""

# Aula 4 - Funções e Modularização - Exercício 5
# Utilização de "reverse"
def ListaInvert(Lista_Origem):
    Lista_Origem.reverse()
    return Lista_Origem

# Lista original
Lista = [1, 2, 3, 4, 5]

# Imprimindo a lista
print("Lista inicial")
print(Lista)

# Chamando a função
Lista_Invertida = ListaInvert(Lista)

# Imprimindo a lista invertida
print("Lista invertida")
print(Lista_Invertida)
print(Lista)