# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""

# Aula 4 - Funções e Modularização - Exercício 2
# Função que verifique se um número é primo.
def Num_Primo(numero):
  for i in range(2, numero):
    if numero % i == 0:
      return False
  return True

numPrimo = int(input("Informe um número inteiro: "))
if Num_Primo(numPrimo):
  print(f"O número {numPrimo} é primo")
else:
  print(f"O número {numPrimo} não é primo")
