# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""
# Aula 4 - Funções e Modularização - Example 4
# Uma function com argumentos padrão
def saudacao(nome="Convidado (a)", saudacao="Olá"):
  #"""Cumprimenta uma pessoa com uma saudação e um nome opcionais."""
  print(f"{saudacao}, {nome}!")

# Utilizando a function
saudacao()  # Usa argumentos padrão
saudacao("Alice") # Usa saudação padrão
saudacao("Rocha", "Bom dia") # Fornece ambos os argumentos
