# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""
# Aula 4 - Funções e Modularização - Example 1
# function para calcular área do retângulo
def calculate_rectangle_area(comprimento, largura):
  area = comprimento * largura
  print(area)
  return area

# Utilizando a função "def"
medida1 = float(input("Informe o valor do comprimento do retângulo: "))
medida2 = float(input("Informe o valor da largura do retângulo: "))
outro = calculate_rectangle_area(medida1, medida2)
print(outro)
print(f"A área do reângulo de {medida1} e largura {medida2} é: {calculate_rectangle_area(medida1, medida2)}")
