# -*- coding: utf-8 -*-
"""Aula04 - Funções e Modularização.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiTmljjGFgtr72OdONxpn1XQ5ZlFJoPU

# Funções e Modularização
"""

# Aula 4 - Funções e Modularização - Exercício 4
# Data a lista abaixo, inverta a ordem dos números.
def ListaInvert(Lista_Origem):
  Lista_Inverte = Lista_Origem [::-1]
  return Lista_Inverte

# Lista original
Lista = [1, 2, 3, 4, 5]

# Chamando a função
Lista_Final = ListaInvert(Lista)

# Imprimindo as listas
print("Lista inicial")
print(Lista)
print("Lista invertida")
print(Lista_Final)
